os: Visual Studio 2015

environment:
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: nightly

install:
- ps: .\appveyor_rust_install.ps1

build_script:
- cmd: cargo build --verbose

test_script:
- cmd: cargo test --verbose

branches:
  only:
    - master
