[package]
name = "read-process-memory"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2.15"
log = "0.3.6"

[target.'cfg(target_os="macos")'.dependencies]
mach = "0.0.5"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[build-dependencies]
skeptic = "0.5"

[dev-dependencies]
skeptic = "0.5"
